name: Benchmark
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        java: [11]
        gradle: [5.6.4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ matrix.gradle }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: ${{ matrix.gradle }}
          arguments: benchmark --parallel --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: benchmark-result
          path: bench/build/reports/jmh/result.json
